[project]
name = "2026fall"
version = "0.1.0"
description = "USTC Principles and Techniques of Compiler (H) 2026 course homepage"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mdx-spanner>=0.1.0",
    "mdx-truly-sane-lists>=1.3",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.20",
]
